import com.AdvInsurance.webservices.AdvInsurance.entity_classes.Claims;
import com.AdvInsurance.webservices.AdvInsurance.entity_classes.Cpt_Codes;
import com.AdvInsurance.webservices.AdvInsurance.entity_classes.Icd_Codes;
import java.time.LocalDate;
import java.time.Period;


#Rule 1- Delayed Claim submission
rule "Check Claim Submission Date"
when
    $claim: Claims($serviceDate : serviceDate, $submissionDate : submissionDate, $eligibility : eligibility == null)
    eval($submissionDate >= $serviceDate && $submissionDate <= $serviceDate.plusMonths(1))
then
    $claim.setEligibility("Not Eligible");
else
    $claim.setEligibility("Eligible");
end

#Rule 2
rule "Check Total Charges"
when
    $claim: Claims($amountBilled : amountBilled, $eligibility : eligibility == null)
    $Cpt_Codes: Cpt_Codes()
    $Icd_Codes: Icd_Codes()
    eval($amountBilled > ($Icd_Codes.getCharge() + $Cpt_Codes.getCharge()))
then
    $claim.setEligibility("Not Eligible");
else
    $claim.setEligibility("Eligible");
end







