import com.AdvInsurance.webservices.AdvInsurance.entity_classes.Claims;
import com.AdvInsurance.webservices.AdvInsurance.entity_classes.Cpt_Codes;
import com.AdvInsurance.webservices.AdvInsurance.entity_classes.Icd_Codes;
import java.time.LocalDate;
import java.time.Period;
import java.time.temporal.ChronoUnit;


rule "Check Claim Submission Date"
when
    $claims: Claims($serviceDate : date_of_service, $submissionDate : date_of_submission, $eligibility : eligibility == "")
    eval(
        $submissionDate.compareTo($serviceDate) >= 0 &&
        ChronoUnit.MONTHS.between($serviceDate, $submissionDate) <= 1
    )
then
    $claims.setEligibility("Eligible");
end


/*
#Rule 2
rule "Check Total Charges"
when
$claim: Claims($amountBilled : amountBilled, $eligibility : eligibility == null)
$Cpt_Codes: Cpt_Codes()
$Icd_Codes: Icd_Codes()
eval($amountBilled > ($Icd_Codes.getCharge() + $Cpt_Codes.getCharge()))
then
$claim.setEligibility("Not Eligible");
else
$claim.setEligibility("Eligible");
end

# Rule 3: Check vision claim eligibility based on age and type of claim
rule "Check Vision Claim Eligibility"
when
$claim: Claims($eligibility : eligibility == null, $typeOfClaim : typeOfClaim == "Vision", $dob : dob)
eval(Period.between($dob, LocalDate.now()).getYears() >= 10)
then
$claim.setEligibility("Eligible");
else
$claim.setEligibility("Not Eligible");
end

# Rule 4: Check dental claim eligibility based on age and type of claim
rule "Check Dental Claim Eligibility"
when
$claim: Claims($eligibility : eligibility == null, $typeOfClaim : typeOfClaim == "Dental", $dob : dob)
eval(Period.between($dob, LocalDate.now()).getYears() >= 5)
then
$claim.setEligibility("Eligible");
else
$claim.setEligibility("Not Eligible");
end
*/







