import com.AdvInsurance.webservices.AdvInsurance.entity_classes.Claims;
import com.AdvInsurance.webservices.AdvInsurance.entity_classes.Cpt_Codes;
import com.AdvInsurance.webservices.AdvInsurance.entity_classes.Icd_Codes;
import java.time.LocalDate;
import java.time.Period;



rule "Check Claim Submission Date"
when
    Claims: Claims(submissionDate >= serviceDate && submissionDate <= serviceDate.plusMonths(1))
then
    $claim.setEligibility("Not Eligible");
else
    $claim.setEligibility("Eligible");
end








